//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_MSGWIN                      100
#define IDD_MSG                         101
#define IDD_MSGSENDERROR                102
#define IDD_CONFIRM_SENDALL             103
#define IDD_OPT_MAIN					110
#define IDD_OPT_MSGDLG                  111
#define IDD_OPT_MSGLOG                  113
#define IDD_OPT_MSGTYPE                 114
#define IDI_ADDCONTACT                  120
#define IDI_USERDETAILS                 121
#define IDI_HISTORY                     122
#define IDI_SEND                        123
#define IDI_CANCEL                      124
#define IDI_SMILEY                      125
#define IDI_TYPING                      126
#define IDI_UNICODEON                   127
#define IDI_UNICODEOFF                  128
#define IDI_TIMESTAMP                   129
#define IDI_QUOTE                   	130
#define IDI_INCOMING                    132
#define IDI_OUTGOING                    133
#define IDI_NOTICE                      134
#define IDR_CONTEXT                     180
#define IDC_HYPERLINKHAND               214
#define IDC_DRAGCURSOR					215
#define IDC_TABS                        1000
#define IDC_LOG                         1001
#define IDC_MESSAGE                     1002
#define IDC_AUTOPOPUP                   1003
#define IDC_AUTOCLOSE                   1004
#define IDC_AUTOMIN                     1005
#define IDC_STAYMINIMIZED				1006
#define IDC_SWITCHTOACTIVE				1007
#define IDC_SPLITTER                    1017
#define IDC_SHOWNAMES                   1020
#define IDC_SHOWSENDBTN                 1021
#define IDC_USETABS                     1022
#define IDC_SHOWSECONDS                 1023
#define IDC_USELONGDATE                 1024
#define IDC_USERELATIVEDATE             1025
#define IDC_USEIEVIEW					1026
#define IDC_SHOWLOGICONS                1032
#define IDC_SHOWTIMES                   1033
#define IDC_SHOWDATES                   1034
#define IDC_CLIST                       1035
#define IDC_SHOWSTATUSCHANGES           1035
#define IDC_GROUPMESSAGES               1036
#define IDC_SAVEPERCONTACT              1037
#define IDC_SAVESPLITTERPERCONTACT      1038
#define IDC_LOADCOUNTN                  1039
#define IDC_LOADCOUNTSPIN               1040
#define IDC_SHOWINFOLINE                1041
#define IDC_SHOWSTATUSBAR               1041
#define IDC_SHOWBUTTONLINE              1042
#define IDC_LOADUNREAD                  1043
#define IDC_SENDONENTER                 1043
#define IDC_LOADCOUNT                   1044
#define IDC_SENDONDBLENTER              1044
#define IDC_LOADTIMEN                   1045
#define IDC_LOADTIMESPIN                1046
#define IDC_LOADTIME                    1047
#define IDC_FONTLIST                    1048
#define IDC_CHOOSEFONT                  1049
#define IDC_SHOWTITLEBAR                1050
#define IDC_STMINSOLD                   1051
#define IDC_SHOWPROGRESS                1052
#define IDC_DETAILS                     1069
#define IDC_ADD                         1070
#define IDC_USERMENU                    1071
#define IDC_QUOTE						1072
#define IDC_HISTORY                     1080
#define IDC_SMILEYS                     1081
#define IDC_REMEMBER					1082
#define IDC_BKGCOLOUR                   1269
#define IDC_BKGINPUT					1270
#define IDC_BKGINCOMING					1271
#define IDC_BKGOUTGOING					1272
#define IDC_FONTCOLOUR                  1282
#define IDC_STMSGLOGGROUP               1442
#define IDC_ERRORTEXT                   1596
#define IDC_MSGTEXT                     1597
#define IDC_SHOWNOTIFY                  1600
#define IDC_STATUSWIN                   1601
#define IDC_TYPEWIN                     1602
#define IDC_CHARCOUNT                   1603
#define IDC_TYPETRAY                    1603
#define IDC_TABSATBOTTOM                1603
#define IDC_CASCADE                     1604
#define IDC_SECONDS                     1605
#define IDC_NOTIFYTRAY                  1606
#define IDC_NOTIFYBALLOON               1607
#define IDC_CTRLSUPPORT                 1608
#define IDC_DELTEMP                     1609
#define IDC_AVATAR                      1610
#define IDC_AVATARSUPPORT               1611
#define IDC_LIMITAVATARH                1612
#define IDC_AVATARHEIGHT                1613
#define IDC_AVATARHEIGHTMIN             1614
#define IDC_LIMITNAMES                  1615
#define IDC_TRANSPARENCY                1616
#define IDC_MARKFOLLOWUPS               1617
#define IDC_MESSAGEONNEWLINE            1618
#define IDC_ATRANSPARENCYVALUE			1619
#define IDC_ATRANSPARENCYPERC           1620
#define IDC_ITRANSPARENCYVALUE			1621
#define IDC_ITRANSPARENCYPERC           1622
#define IDC_HIDEONETAB					1623
#define IDC_SENDALL						1624
#define IDC_AVATARTEXT1                 1625
#define IDC_AVATARTEXT2					1626
#define IDC_TRANSPARENCYTEXT1			1627
#define IDC_TRANSPARENCYTEXT2			1628
#define IDC_DRAWLINES					1629
#define IDC_LINECOLOUR					1630
#define IDC_SAVEDRAFTS					1631
#define IDC_POPLIST						1632
#define IDM_CUT                         40000
#define IDM_COPY                        40001
#define IDM_PASTE                       40002
#define IDM_UNDO                        40003
#define IDM_DELETE                      40004
#define IDM_REDO                        40005
#define IDM_COPYALL                     40011
#define IDM_SELECTALL                   40012
#define IDM_CLEAR                       40013
#define IDM_OPENNEW                     40014
#define IDM_OPENEXISTING                40015
#define IDM_COPYLINK                    40016
#define IDM_CLOSETAB					40020
#define IDM_CLOSEOTHERTABS				40021
#define IDM_TOPMOST						40040

/* chat.dll resources */

#define IDD_CHANNEL                     401
#define IDD_OPTIONS1                    402
#define IDD_OPTIONS2                    403
#define IDD_FILTER                      405
#define IDD_OPTIONSPOPUP                406
#define IDI_BUNDERLINE                  420
#define IDI_BBOLD                       421
#define IDI_BITALICS                    422
#define IDI_BSMILEY                     423
#define IDI_TOPICBUT                    424
#define IDI_BKGCOLOR                    425
#define IDI_CHANMGR                     426
#define IDI_COLOR                       427
#define IDI_FILTER                      428
#define IDI_CHAT_HISTORY                429
#define IDI_NICKLIST                    430
#define IDI_JOIN                        431
#define IDI_PART                        432
#define IDI_QUIT                        433
#define IDI_KICK                        434
#define IDI_NICK                        435
#define IDI_CHAT_NOTICE                 436
#define IDI_MESSAGE                     437
#define IDI_MESSAGEOUT                  438
#define IDI_TOPIC                       439
#define IDI_INFO                        440
#define IDI_ADDSTATUS                   441
#define IDI_REMSTATUS                   442
#define IDI_ACTION                      443
#define IDI_HIGHLIGHT                   444
#define IDI_BLANK                       446
#define IDI_TAG1                        449
#define IDI_TAG2                        450
#define IDR_MENU                        451
#define IDD_COLORCHOOSER                452
#define IDI_STATUS3                     453
#define IDI_STATUS2                     454
#define IDI_STATUS4                     455
#define IDI_STATUS1                     456
#define IDI_STATUS0                     457
#define IDI_STATUS5                     458
#define IDI_CLOSE                       459
#define IDI_OVERLAY                     460
#define IDI_NICKLIST2                   461
#define IDI_FILTER2                     462
#define IDC_CHAT_LOG                         5005
#define IDC_CHAT_SPLITTERX                   5006
#define IDC_CHAT_SMILEY                      5007
#define IDC_CHAT_SPLITTERY                   5008
#define IDC_CHAT_MESSAGE                     5009
#define IDC_CHAT_BOLD                        5010
#define IDC_CHAT_ITALICS                     5011
#define IDC_CHAT_UNDERLINE                   5012
#define IDC_CHAT_FILTER                      5013
#define IDC_CHAT_CHANMGR                     5014
#define IDC_CHAT_SHOWNICKLIST                5016
#define IDC_CHAT_COLOR                       5017
#define IDC_CHAT_BKGCOLOR                    5019
#define IDC_CHAT_CHECKBOXES                  5021
#define IDC_CHAT_NICKLISTBKG                 5021
#define IDC_CHAT_HISTORY                     5022
#define IDC_CHAT_CLOSE                       5023
#define IDC_CHAT_NICKROW                     5024
#define IDC_CHAT_LOGLIMIT                    5024
#define IDC_CHAT_SPIN1                       5028
#define IDC_CHAT_SPIN2                       5029
#define IDC_CHAT_SPIN3                       5030
#define IDC_CHAT_FONTLIST                    5032
#define IDC_CHAT_CHOOSEFONT                  5034
#define IDC_CHAT_FONTCOLOR                   5035
#define IDC_CHAT_MESSAGEBKG                  5036
#define IDC_CHAT_LOGBKG                      5037
#define IDC_CHAT_HIGHLIGHTWORDS              5040
#define IDC_CHAT_INSTAMP                     5041
#define IDC_CHAT_OUTSTAMP                    5043
#define IDC_CHAT_TIMESTAMP                   5046
#define IDC_CHAT_FONTCHOOSE                  5047
#define IDC_CHAT_LOGDIRECTORY                5048
#define IDC_CHAT_LIMIT                       5050
#define IDC_CHAT_LOGTIMESTAMP                5051
#define IDC_CHAT_GROUP                       5057
#define IDC_CHAT_RADIO1                      5061
#define IDC_CHAT_RADIO2                      5062
#define IDC_CHAT_RADIO3                      5063
#define IDC_CHAT_TEXT                        5064
#define IDC_CHAT_BKG                         5065
#define IDC_CHAT_TIMEOUT                     5067
#define IDC_CHAT_HIGHLIGHT                   5068
#define IDC_CHAT_TEXTO                       5069
#define IDC_CHAT_LOGGING                     5069
#define IDC_CHAT_COLORTEXT                   5070
#define IDC_CHAT_LIST                        5072
#define IDC_CHAT_1                           5075
#define IDC_CHAT_2                           5076
#define IDC_CHAT_3                           5077
#define IDC_CHAT_4                           5078
#define IDC_CHAT_5                           5079
#define IDC_CHAT_6                           5080
#define IDC_CHAT_7                           5081
#define IDC_CHAT_8                           5082
#define IDC_CHAT_9                           5083
#define IDC_CHAT_10                          5084
#define IDC_CHAT_11                          5085
#define ID_MESS                         50001
#define ID_NEW                          50002
#define ID_CURR                         50003
#define ID_COPY                         50004
#define ID_COPYALL                      50006
#define ID_CLEARLOG                     50009
#define ID_MESSAGE_UNDO                 50013
#define ID_MESSAGE_COPY                 50014
#define ID_MESSAGE_CUT                  50015
#define ID_MESSAGE_CLEAR                50017
#define ID_MESSAGE_SELECTALL            50018
#define ID_MESSAGE_REDO                 50019
#define ID_MESSAGE_PASTE                50020
#define ID_CLOSE                        50022
#define ID_CLOSEOTHER                   50023
#define ID_LOCKPOSITION                 50024
#define ID_Menu                         50026
#define ID_SEARCH_GOOGLE                50027
#define ID_SEARCH_WIKIPEDIA             50028
#define ID_WIKIPEDIA_                   50029
