//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by msvc6.rc
//
#ifndef _WIN32_IE
#define _WIN32_IE 0x0400
#endif

#define IDCANCEL2                       3
#define IDD_OPT_JABBER                  101
#define IDI_JABBER                      102
#define IDD_INFO_JABBER                 103
#define IDD_OPT_REGISTER                105
#define IDD_AGENTS                      106
#define IDD_FORM                        107
//#define IDI_ADDROSTER                   108
//#define IDI_USER2ROOM                   109
#define IDD_PASSWORD                    111
//#define IDI_TLEN                        121
#define IDB_ICONSSMALL                  122
#define IDB_ICONSBIG                    123
//#define IDI_ADDCONTACT                  122
//#define IDI_DELETE                      123
//#define IDI_EDIT                        124
#define IDD_VCARD                       125
#define IDD_VCARD_HOME                  126
#define IDD_VCARD_PERSONAL              127
#define IDD_VCARD_WORK                  128
#define IDD_VCARD_CONTACT               129
#define IDD_VCARD_ADDEMAIL              130
#define IDD_VCARD_ADDPHONE              131
//#define IDI_OPEN                        131
#define IDD_VCARD_PHOTO                 132
#define IDD_VCARD_NOTE                  133
#define IDD_CHANGEPASSWORD              136
#define IDD_OPT_JABBER2                 140
//#define IDI_REQUEST                     141
#define IDD_GROUPCHAT                   141
//#define IDI_GRANT                       142
//#define IDI_KEYS                        144
//#define IDI_GROUP                       147
#define IDD_GROUPCHAT_JOIN              148
//#define IDI_AGENTS                      154
//#define IDI_VCARD                       155
//#define IDI_WRITE                       162
//#define IDI_SAVE                        166
#define IDD_GROUPCHAT_INPUT             167
#define IDD_ADVSEARCH_TLEN              169
#define IDD_JIDLIST                     171
#define IDD_AGENT_MANUAL_REGISTER       182
#define IDD_GROUPCHAT_INVITE            183
#define IDD_GROUPCHAT_INVITE_ACCEPT     184
#define IDD_OPT_JABBER3                 185
#define IDD_OPT_SETAVATAR               185
//#define IDI_MAIL_NEW                    186
//#define IDI_MAIL_STOP                   187
//#define IDI_MAIL_INFO                   188
//#define IDI_MAIL_CLOCK                  189
//#define IDI_MAIL_GMAIL                  190
#define IDD_OPT_EXPERT                  190
#define IDC_OPT_EXPERT_TAB              191
#define IDD_OPT_JGMAIL                  192
#define IDC_ENGMAIL                     193
#define IDC_SHOWREQUEST                 195
#define IDC_SHOWRESULT                  196
#define IDC_SYNCHRONIZE                 197
#define IDC_SYNCHRONIZESILENT           198
#define IDC_VISITGMAIL                  199
#define IDC_INVASUNAVAIL                200
#define IDC_ENGMAILSTARTUP              201
#define IDC_PREVIEW                     202
#define IDC_COLOURTEXT                  203
#define IDC_COLOURBACK                  204
#define IDC_USEPOPUP                    205
#define IDC_EDIT_TIMEOUT                206
#define IDC_DEBUGCOLOURTEXT             207
#define IDC_DEBUGCOLOURBACK             208
#define IDC_EDIT_DEBUGTIMEOUT           209
#define IDC_ERRORCOLOURTEXT             210
#define IDC_ERRORCOLOURBACK             211
#define IDC_USEFAKE                     212
#define IDC_EDIT_ERRORTIMEOUT           213
#define IDC_CLOCKCOLOURTEXT             214
#define IDC_CLOCKCOLOURBACK             215
#define IDC_EDIT_CLOCKTIMEOUT           216
#define IDC_RESET                       217
#define IDC_FORCECHECK                  218
#define IDC_SAVECHATS                   219
#define IDC_SUPERR                      220
#define IDC_SUPREREQUEST                221
#define IDC_CHECKTIMES                  222
#define IDC_EDIT_LABELS                 223
#define IDC_SHOWLABELS                  224
#define IDC_EXPERTLABELS                225
#define IDC_EDIT_USERNAME               1000
#define IDC_SAVE                        1000
#define IDC_EDIT_PASSWORD               1001
#define IDC_BUTTON_REGISTER             1002
#define IDC_EDIT_LOGIN_SERVER           1003
#define IDC_PORT                        1004
#define IDC_EDIT_RESOURCE               1005
#define IDC_INFO_JID                    1007
#define IDC_INFO_RESOURCE               1008
#define IDC_LINK_PUBLIC_SERVER          1009
#define IDC_NAME                        1009
#define IDC_LINK_PUBLIC_SERVER2         1010
#define IDC_DOWNLOAD_OPENSSL            1010
#define IDC_PROGRESS_REG                1011
#define IDOK2                           1012
#define IDC_AGENT_TRANSPORT             1015
#define IDC_AGENT_REGISTER              1016
#define IDC_AGENT_LOGON                 1017
#define IDC_AGENT_UNREGISTER            1018
#define IDC_AGENT_SERVER                1019
#define IDC_AGENT_LOGOFF                1020
#define IDC_AGENT_LIST                  1021
#define IDC_AGENT_SEARCH                1022
#define IDC_SUBMIT                      1023
#define IDC_LOGO                        1024
#define IDC_AGENT_BROWSE                1029
#define IDC_INSTRUCTION                 1030
#define IDC_DESCRIPTION                 1031
#define IDC_FRAME                       1037
#define IDC_FRAME_TEXT                  1038
#define IDC_SUBSCRIPTION                1039
#define IDC_SIMPLE                      1041
#define IDC_KEEPALIVE                   1042
#define IDC_HOST                        1043
#define IDC_HOSTPORT                    1044
#define IDC_USE_SSL                     1045
#define IDC_MANUAL                      1046
#define IDC_RESOURCE_T                  1047
#define IDC_SAVEPASSWORD                1048
#define IDC_MSGLANG                     1049
#define IDC_PASSWORD                    1050
#define IDC_JID                         1051
#define IDC_NEWPASSWD2                  1052
#define IDC_ROSTER_SYNC                 1052
#define IDC_OLDPASSWD                   1053
#define IDC_ADDRESS1                    1056
#define IDC_ADDRESS2                    1057
#define IDC_CITY                        1058
#define IDC_STATE                       1059
#define IDC_COUNTRY                     1060
#define IDC_FULLNAME                    1061
#define IDC_ZIP                         1061
#define IDC_NICKNAME                    1062
#define IDC_COMPANY                     1062
#define IDC_FIRSTNAME                   1063
#define IDC_DEPARTMENT                  1063
#define IDC_LASTNAME                    1064
#define IDC_BIRTH                       1065
#define IDC_OCCUPATION                  1066
#define IDC_HOMEPAGE                    1067
#define IDC_AVATAR                      1068
#define IDC_ENABLE_AVATARS              1069
#define IDC_SETAVATAR                   1070
#define IDC_DELETEAVATAR                1071
#define IDC_MIDDLE                      1072
#define IDC_EMAIL                       1073
#define IDC_HOME                        1074
#define IDC_INTERNET                    1075
#define IDC_X400                        1076
#define IDC_WORK                        1077
#define IDC_PHONE                       1078
#define IDC_CELL                        1079
#define IDC_VIDEO                       1080
#define IDC_BBS                         1081
#define IDC_MODEM                       1082
#define IDC_PAGER                       1083
#define IDC_MSG                         1084
#define IDC_ISDN                        1085
#define IDC_PCS                         1086
#define IDC_VOICE                       1087
#define IDC_FAX                         1088
#define IDC_TITLE                       1089
#define IDC_DESC                        1090
#define IDC_DELETE                      1092
#define IDC_LOAD                        1093
#define IDC_CANVAS                      1094
#define IDC_GENDER                      1096
#define IDC_JUD                         1097
#define IDC_JUD_LABEL                   1098
#define IDC_MSGLANG_LABEL               1099
#define IDC_SOFTWARE                    1101
#define IDC_VERSION                     1102
#define IDC_SYSTEM                      1103
#define IDC_PRIORITY_SPIN               1104
#define IDC_PRIORITY                    1105
#define IDC_PRIORITY_LABEL              1106
#define IDC_NEWPASSWD                   1107
#define IDC_PASS_SERVER                 1112
#define IDC_PROXY_ADDR                  1112
#define IDC_PASS_PORT                   1113
#define IDC_EXT_ADDRESS                 1114
#define IDC_DIRECT_ADDR                 1114
#define IDC_SHOW_TRANSPORT              1115
#define IDC_AUTO_ADD                    1116
#define IDC_PASS_SERVER_LABEL           1117
#define IDC_EXT_ADDRESS_LABEL           1118
#define IDC_PASS_PORT_LABEL             1119
#define IDC_USE_PASS                    1120
#define IDC_PROXY                       1120
#define IDC_USE_EXT_ADDRESS             1121
#define IDC_DIRECT_MANUAL               1121
#define IDC_REG_STATUS                  1122
#define IDC_MSG_ACK                     1122
#define IDC_JOIN                        1123
#define IDC_DIRECT                      1123
#define IDC_ROOM                        1124
#define IDC_PROXY_MANUAL                1124
#define IDC_SERVER                      1125
#define IDC_BROWSE                      1126
#define IDC_VSCROLL                     1128
#define IDC_NICK                        1129
#define IDC_EDIT                        1131
#define IDC_LIST                        1133
#define IDC_HSPLIT                      1134
#define IDC_LOG                         1136
#define IDC_VSPLIT                      1137
#define IDC_SET                         1140
#define IDC_TABS                        1141
#define IDC_TOPIC                       1141
#define IDC_FONT                        1143
#define IDC_ENTER                       1144
#define IDC_CTRLENTER                   1145
#define IDC_FONTSHOW                    1146
#define IDC_FLASH                       1148
#define IDC_AGEFROM                     1152
#define IDC_AGETO                       1153
#define IDC_LOOKFOR                     1154
#define IDC_SCHOOL                      1155
#define IDC_TIME                        1156
#define IDC_DATE                        1157
#define IDC_MANUAL_REGISTER             1167
#define IDC_REASON                      1171
#define IDC_USER                        1172
#define IDC_INVITE                      1173
#define IDC_ACCEPT                      1174
#define IDC_FROM                        1175
#define IDC_AUTOJOIN                    1176
#define IDC_DISABLE_MAINMENU            1178
#define IDC_USE_TLS                     1179
#define IDC_AUTO_ACCEPT_MUC             1180
#define IDC_DISABLE_SASL                1182
#define IDC_WHITERECT                   1221
#define IDC_UPDATING                    1231
#define IDC_EMAILS                      1306
#define IDC_PHONES                      1308
#define IDC_UPDATE                      1313
#define IDC_STATUS                      1414
#define IDC_PLAN                        1415
#define IDC_PERSONALGROUP               1434
#define IDC_EXTRAGROUP                  1436
#define IDM_MESSAGE                     10002
#define IDM_CLEAR                       10003
#define IDM_VOICE                       10005
#define IDM_BAN                         10006
#define IDM_ADMIN                       10007
#define IDM_OWNER                       10008
#define IDM_CONFIG                      10009
#define IDM_KICK                        10011
#define IDM_NICK                        10012
#define IDM_MODERATOR                   10013
#define IDM_DESTROY                     10014
#define IDM_MEMBER                      10015
#define IDM_INVITE                      10016

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        226
#define _APS_NEXT_COMMAND_VALUE         40017
#define _APS_NEXT_CONTROL_VALUE         1183
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
