//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by chat.rc
//
#define IDD_CHANNEL                     401
#define IDD_OPTIONS1                    402
#define IDD_OPTIONS2                    403
#define IDD_FILTER                      405
#define IDD_OPTIONSPOPUP                406
#define IDI_BUNDERLINE                  420
#define IDI_BBOLD                       421
#define IDI_BITALICS                    422
#define IDI_BSMILEY                     423
#define IDI_TOPICBUT                    424
#define IDI_BKGCOLOR                    425
#define IDI_CHANMGR                     426
#define IDI_COLOR                       427
#define IDI_FILTER                      428
#define IDI_CHAT_HISTORY                429
#define IDI_NICKLIST                    430
#define IDI_JOIN                        431
#define IDI_PART                        432
#define IDI_QUIT                        433
#define IDI_KICK                        434
#define IDI_NICK                        435
#define IDI_CHAT_NOTICE                 436
#define IDI_MESSAGE                     437
#define IDI_MESSAGEOUT                  438
#define IDI_TOPIC                       439
#define IDI_INFO                        440
#define IDI_ADDSTATUS                   441
#define IDI_REMSTATUS                   442
#define IDI_ACTION                      443
#define IDI_HIGHLIGHT                   444
#define IDI_BLANK                       446
#define IDI_TAG1                        449
#define IDI_TAG2                        450
#define IDR_MENU                        451
#define IDD_COLORCHOOSER                452
#define IDI_STATUS3                     453
#define IDI_STATUS2                     454
#define IDI_STATUS4                     455
#define IDI_STATUS1                     456
#define IDI_STATUS0                     457
#define IDI_STATUS5                     458
#define IDI_CLOSE                       459
#define IDI_OVERLAY                     460
#define IDI_NICKLIST2                   461
#define IDI_FILTER2                     462
#define IDC_CHAT_LOG                         5005
#define IDC_CHAT_SPLITTERX                   5006
#define IDC_CHAT_SMILEY                      5007
#define IDC_CHAT_SPLITTERY                   5008
#define IDC_CHAT_MESSAGE                     5009
#define IDC_CHAT_BOLD                        5010
#define IDC_CHAT_ITALICS                     5011
#define IDC_CHAT_UNDERLINE                   5012
#define IDC_CHAT_FILTER                      5013
#define IDC_CHAT_CHANMGR                     5014
#define IDC_CHAT_SHOWNICKLIST                5016
#define IDC_CHAT_COLOR                       5017
#define IDC_CHAT_BKGCOLOR                    5019
#define IDC_CHAT_CHECKBOXES                  5021
#define IDC_CHAT_NICKLISTBKG                 5021
#define IDC_CHAT_HISTORY                     5022
#define IDC_CHAT_CLOSE                       5023
#define IDC_CHAT_NICKROW                     5024
#define IDC_CHAT_LOGLIMIT                    5024
#define IDC_CHAT_SPIN1                       5028
#define IDC_CHAT_SPIN2                       5029
#define IDC_CHAT_SPIN3                       5030
#define IDC_CHAT_FONTLIST                    5032
#define IDC_CHAT_CHOOSEFONT                  5034
#define IDC_CHAT_FONTCOLOR                   5035
#define IDC_CHAT_MESSAGEBKG                  5036
#define IDC_CHAT_LOGBKG                      5037
#define IDC_CHAT_HIGHLIGHTWORDS              5040
#define IDC_CHAT_INSTAMP                     5041
#define IDC_CHAT_OUTSTAMP                    5043
#define IDC_CHAT_TIMESTAMP                   5046
#define IDC_CHAT_FONTCHOOSE                  5047
#define IDC_CHAT_LOGDIRECTORY                5048
#define IDC_CHAT_LIMIT                       5050
#define IDC_CHAT_LOGTIMESTAMP                5051
#define IDC_CHAT_GROUP                       5057
#define IDC_CHAT_RADIO1                      5061
#define IDC_CHAT_RADIO2                      5062
#define IDC_CHAT_RADIO3                      5063
#define IDC_CHAT_TEXT                        5064
#define IDC_CHAT_BKG                         5065
#define IDC_CHAT_TIMEOUT                     5067
#define IDC_CHAT_HIGHLIGHT                   5068
#define IDC_CHAT_TEXTO                       5069
#define IDC_CHAT_LOGGING                     5069
#define IDC_CHAT_COLORTEXT                   5070
#define IDC_CHAT_LIST                        5072
#define IDC_CHAT_TAB                         5074
#define IDC_CHAT_1                           5075
#define IDC_CHAT_2                           5076
#define IDC_CHAT_3                           5077
#define IDC_CHAT_4                           5078
#define IDC_CHAT_5                           5079
#define IDC_CHAT_6                           5080
#define IDC_CHAT_7                           5081
#define IDC_CHAT_8                           5082
#define IDC_CHAT_9                           5083
#define IDC_CHAT_10                          5084
#define IDC_CHAT_11                          5085
#define ID_MESS                         50001
#define ID_NEW                          50002
#define ID_CURR                         50003
#define ID_COPY                         50004
#define ID_COPYALL                      50006
#define ID_CLEARLOG                     50009
#define ID_MESSAGE_UNDO                 50013
#define ID_MESSAGE_COPY                 50014
#define ID_MESSAGE_CUT                  50015
#define ID_MESSAGE_CLEAR                50017
#define ID_MESSAGE_SELECTALL            50018
#define ID_MESSAGE_REDO                 50019
#define ID_MESSAGE_PASTE                50020
#define ID_CLOSE                        50022
#define ID_CLOSEOTHER                   50023
#define ID_LOCKPOSITION                 50024
#define ID_Menu                         50026
#define ID_SEARCH_GOOGLE                50027
#define ID_SEARCH_WIKIPEDIA             50028
#define ID_WIKIPEDIA_                   50029

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4163
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
